language: php
sudo: false
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer install

script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] ; then ./vendor/bin/phpcs --standard=vendor/internations/kodierungsregelwerksammlung/ruleset.xml ./src/ ; fi'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ] ; then mkdir build/coverage ; fi'
  - phpunit
