language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer install

script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] ; then ./vendor/bin/phpcs --ignore="*/Tests/*" --standard=vendor/internations/kodierungsregelwerksammlung/ruleset.xml ./src/ ; fi'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ] ; then mkdir build/coverage ; fi'
  - phpunit

notifications:
  email:
    - lars.strojny@internations.org
    - max.beutel@internations.org
    - marc.jakubowski@internations.org
    - michael.weinrich@internations.org
    - vitor.balocco@internations.org
